workflow:
  as: cucushift-installer-rehearse-azure-aks-hypershift-disaster-recovery-infra-guest
  steps:
    cluster_profile: azure-hcp-ha-qe
    pre:
    - chain: cucushift-installer-rehearse-azure-aks-hypershift-disaster-recovery-infra-provision
    - ref: cucushift-hypershift-extended-enable-guest
    post:
    - ref: cucushift-hypershift-extended-disable-guest
    - chain: cucushift-installer-rehearse-azure-aks-hypershift-disaster-recovery-infra-deprovision
